export * from './MoviesListCard/MoviesListCard'
export * from './MoviesListCard/MovieInfo'
export * from './MoviesListCard/Picture'
export * from './MoviesListCard/StarsRating'
export * from './Header/Header'
export * from './Header/Switch'
export * from './MoviesList/MoviesList'
export * from './MoviesListCard/Recommendation_Page'